DROP TABLE IF EXISTS CONTRACT;
DROP TABLE IF EXISTS CONTRACT_TYPE;
DROP TABLE IF EXISTS EMPLOYEE;

CREATE TABLE EMPLOYEE(EMPLOYEE_ID INT auto_increment PRIMARY KEY, BIRTH_DATE DATE, CELL_PHONE VARCHAR(255),DATE_CREATED DATE, EMAIL VARCHAR(255), IS_ACTIVE INT, LAST_NAME VARCHAR(255), NAME VARCHAR(255), TAX_ID_NUMBER VARCHAR(255));
CREATE TABLE CONTRACT_TYPE(CONTRACT_TYPE_ID INT auto_increment PRIMARY KEY, DATE_CREATE DATE,DESCRIPTION VARCHAR(255), IS_ACTIVE INT,NAME VARCHAR(255));
CREATE TABLE CONTRACT(CONTRACT_ID INT auto_increment PRIMARY KEY, DATE_CREATED DATE, DATE_FORM DATE, DATE_TO DATE,IS_ACTIVE INT,SALARY_PER_DAY INT,CONTRACT_TYPE_ID  INT, EMPLOYEE_ID INT);


ALTER TABLE CONTRACT
ADD FOREIGN KEY (EMPLOYEE_ID)
REFERENCES EMPLOYEE (EMPLOYEE_ID);

ALTER TABLE CONTRACT
ADD FOREIGN KEY (CONTRACT_TYPE_ID)
REFERENCES CONTRACT_TYPE (CONTRACT_TYPE_ID );